/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 5.7.24 : Database - skripsi_tiara
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
-- USE `skripsi_tiara`;

/*Table structure for table `admin` */

DROP TABLE IF EXISTS `admin`;

CREATE TABLE `admin` (
  `id_admin` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(30) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_admin`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `admin` */

insert  into `admin`(`id_admin`,`username`,`password`) values 
(1,'admin','$2y$10$38FkPC/fn4YBJKnnxLddC.j8eBMTKqT9T3FsAmB0fop4rgoYZn88O'),
(3,'tiara','$2y$10$Ojum780ZNo34sk/pfMFMUu7c1PvYolnASDRWQYe5zoMgPU0t6aby.');

/*Table structure for table `data_latih` */

DROP TABLE IF EXISTS `data_latih`;

CREATE TABLE `data_latih` (
  `id_data` int(11) NOT NULL AUTO_INCREMENT,
  `id_objek` int(11) DEFAULT NULL,
  `tgl_tweet` datetime DEFAULT NULL,
  `tweet` text,
  `prepos_text` text,
  `kat_sentimen` enum('positif','negatif') DEFAULT NULL,
  PRIMARY KEY (`id_data`)
) ENGINE=InnoDB AUTO_INCREMENT=551 DEFAULT CHARSET=latin1;

/*Data for the table `data_latih` */

insert  into `data_latih`(`id_data`,`id_objek`,`tgl_tweet`,`tweet`,`prepos_text`,`kat_sentimen`) values 
(1,1,'2021-04-09 23:53:16','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #21','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(2,1,'2021-04-09 23:46:54','RT @netmediatama: Mang Ded...? Loohh kok ngamook! ???? https://t.co/jFwOfJe9KV','mang,ded,loohh,ngamook','positif'),
(3,1,'2021-04-09 23:42:43','@netmediatama Spurs vs united min..????','spurs,vs,united,min','positif'),
(4,1,'2021-04-09 23:23:08','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #20','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(5,1,'2021-04-09 22:56:04','So proud of Ilene as the winner of #INTMxNET @netmediatama ????????????','so,proud,of,ilene,as,the,winner,of','negatif'),
(6,1,'2021-04-09 22:55:06','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #19','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(7,1,'2021-04-09 22:36:21','RT @netmediatama: Vincent udah mulai kesel, disuruh main sendiri aja???? https://t.co/U5fB4BdvnW','vincent,udah,kesel,suruh,main,aja','negatif'),
(8,1,'2021-04-09 22:25:30','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #18','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(9,1,'2021-04-09 22:22:13','@netmediatama Blan puasa drakor ada gak min','blan,puasa,drakor,gak,min','positif'),
(10,1,'2021-04-09 22:19:00','@netmediatama Selesai Ramadan Drakor tayang lagi kan min','selesai,ramadan,drakor,tayang,min','negatif'),
(11,1,'2021-04-09 22:11:15','@netmediatama duh tim prabu jd kliatan gk gahar dikerjain sama mas ferdian????????????','duh,tim,prabu,jd,kliatan,gk,gahar,kerjain,mas,ferdian','positif'),
(12,1,'2021-04-09 21:54:07','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #17','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(13,1,'2021-04-09 21:43:31','@netmediatama wkwkww','wkwkww','negatif'),
(14,1,'2021-04-09 21:25:48','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #16','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(15,1,'2021-04-09 20:56:00','@netmediatama @hondaisme niat nonton eh ketiduran????','niat,nonton,eh,tidur','positif'),
(16,1,'2021-04-09 19:52:50','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #15','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(17,1,'2021-04-09 19:24:37','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #14','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(18,1,'2021-04-09 19:14:51','My luv https://t.co/kN01xY8IEz','my,luv','positif'),
(19,1,'2021-04-09 19:03:22','RT @netmediatama: Mang Ded...? Loohh kok ngamook! ???? https://t.co/jFwOfJe9KV','mang,ded,loohh,ngamook','positif'),
(20,1,'2021-04-09 18:54:16','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #13','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(21,1,'2021-04-09 18:24:15','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #12','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(22,1,'2021-04-09 18:15:47','? jd kepikiran apa ilene tampil bagus krna yg dihadirkan adlh kakak2nya yg suportif smntara gea tampil krg bagus kr… https://t.co/o5cSAslxLV','jd,pikir,ilene,tampil,bagus,krna,yg,hadir,adlh,kakak,yg,suportif,smntara,gea,tampil,krg,bagus,kr','positif'),
(23,1,'2021-04-09 18:06:27','buat net @netmediatama bener-bener ditunggu intm cycle 2 nya. plis plis gue saran bgt kurangin drama, cycle 1 aja d… https://t.co/3uaD0LS3iD','net,bener-bener,tunggu,intm,cycle,plis,plis,gue,saran,bgt,kurangin,drama,cycle,aja,d','positif'),
(24,1,'2021-04-09 18:03:17','awww so proud of you ci ilene sama ci gea lah ya ofcourse. udh berjuang sejauh ini dan akhirnya ci ilene jdi the fi… https://t.co/x6FM6LTqNG','awww,so,proud,of,you,ci,ilene,ci,gea,ya,ofcourse,udh,juang,ci,ilene,jdi,the,fi','negatif'),
(25,1,'2021-04-09 18:03:07','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','negatif'),
(26,1,'2021-04-09 17:58:51','? no wonder gestur gea ke ibunya kyk awkward gt di 2 eps trakhir, ga sehangat ke bokapnya\n? yumi cangtip bet di run… https://t.co/NORoXuIDQI','no,wonder,gestur,gea,ibu,kyk,awkward,gt,eps,trakhir,ga,hangat,bokap,yumi,cangtip,bet,run','positif'),
(27,1,'2021-04-09 17:52:42','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #11','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(28,1,'2021-04-09 17:43:19','Bener ya Patricia Gouw totalitas banget sebagai judges/mentor, sampe bagi bagi cuan lagi buat Ilene sama Gea, Shay.… https://t.co/yruCEDjoIt','bener,ya,patricia,gouw,totalitas,banget,judgesmentor,sampe,cuan,ilene,gea,shay','positif'),
(29,1,'2021-04-09 17:24:00','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/TixuIy4z8J','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(30,1,'2021-04-09 17:10:33','netmediatama Jawabannya: Lost without you - Robin Thicke #TwinsNET4 #HUTNET4_21MEI','netmediatama,jawab,lost,without,you,-,robin,thicke','positif'),
(31,1,'2021-04-09 17:02:11','@KristiantiFebe @netmediatama Jd judges juga aku mau sih','jd,judges,sih','positif'),
(32,1,'2021-04-09 17:01:08','@olinenilo @netmediatama With top? Or? Hahahah','with,top,or,hahahah','positif'),
(33,1,'2021-04-09 16:53:25','@tweetgazm Tolong @netmediatama hire teman saya jadi tim kreatif wkwk','tolong,hire,teman,tim,kreatif,wkwk','positif'),
(34,1,'2021-04-09 16:52:53','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/JZubxQpVXy','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(35,1,'2021-04-09 16:33:49','Ilene cantik banget di story Flores. Selamat Ilene The First Indonesia\'s Next Top Model! #intm @netmediatama https://t.co/RoBvebMFa7','ilene,cantik,banget,story,flores,selamat,ilene,the,first,indonesias,next,top,model','positif'),
(36,1,'2021-04-09 16:23:07','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/GhIGF8Uad5','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(37,1,'2021-04-09 16:15:31','Told ya!!! HAHAHAHHA m so happy for Ilene!! yazz Ilene on top!! #intm @netmediatama','told,ya,hahahahha,m,so,happy,for,ilene,yazz,ilene,on,top','negatif'),
(38,1,'2021-04-09 16:14:19','@netmediatama Cieee dikerjain tivi sebelah c i y é','cieee,kerjain,tivi,be,c,i,y','positif'),
(39,1,'2021-04-09 16:14:11','@Galagea78 Congrats KA GEA for Runner up INTM @INTM_NET @netmediatama','congrats,ka,gea,for,runner,up,intm','positif'),
(40,1,'2021-04-09 16:06:46','@netmediatama Wah udah mulai main ginian ????','udah,main,ginian','positif'),
(41,1,'2021-04-09 16:05:17','@netmediatama Ferdian bukan si','ferdian,si','positif'),
(42,1,'2021-04-09 16:05:14','@netmediatama Kaya yg tukang hipnotis di opiji','kaya,yg,tukang,hipnotis,opiji','positif'),
(43,1,'2021-04-09 16:00:40','Ilene tuh emg top model material bgt no debate lahhh, she deserves it, and pls season depan ganti aja  d3ddy ama lu… https://t.co/ab8bCFMO6V','ilene,tuh,emg,top,model,material,bgt,no,debate,lahhh,she,deserves,it,and,pls,ason,ganti,aja,dddy,ama,lu','negatif'),
(44,1,'2021-04-09 16:00:34','RT @netmediatama: Malam-malam lagi tugas, Tim Prabu dikerjain YouTuber nih ???? https://t.co/7pR0x5V8PV','malam-malam,tugas,tim,prabu,kerjain,youtuber,nih','negatif'),
(45,1,'2021-04-09 16:00:01','Malam-malam lagi tugas, Tim Prabu dikerjain YouTuber nih ???? https://t.co/7pR0x5V8PV','malam-malam,tugas,tim,prabu,kerjain,youtuber,nih','negatif'),
(46,1,'2021-04-09 15:57:48','RT @GoRuli: Terima kasih dukungannya teman teman \n\n#ilene #intm @netmediatama https://t.co/taHnUrhxP1','terima,kasih,dukung,teman,teman','positif'),
(47,1,'2021-04-09 15:57:42','@GoRuli @netmediatama rulleneee, rully illeeenee','rulleneee,rully,illeeenee','negatif'),
(48,1,'2021-04-09 15:56:26','@GoRuli @netmediatama Go ruli go!','go,ruli,go','positif'),
(49,1,'2021-04-09 15:55:54','Aaaaa sii cantik Ilene yg jadi The 1st Indonesia\'s Next Top Model !!!\n\nDutunggu INTM cycle 2 nya \n@netmediatama\n \n????????????????','aaaaa,si,cantik,ilene,yg,the,st,indonesias,next,top,model,dutunggu,intm,cycle','positif'),
(50,1,'2021-04-09 15:53:40','@GoRuli @netmediatama Ngakak','ngakak','positif'),
(51,1,'2021-04-09 15:52:44','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/faguZedC38','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(52,1,'2021-04-09 15:52:14','@netmediatama @hondaisme Juara 2 gadapet hadiah?','juara,gadapet,hadiah','positif'),
(53,1,'2021-04-09 15:51:13','Terima kasih dukungannya teman teman \n\n#ilene #intm @netmediatama https://t.co/taHnUrhxP1','terima,kasih,dukung,teman,teman','positif'),
(54,1,'2021-04-09 15:49:13','Congrats Ilene atas kemenangan menjadi The first Indonesian next top model ?\n\nBtw gw kira Gea juga dapet hadiah  te… https://t.co/3QmaS19WHQ','congrats,ilene,menang,the,first,indonesian,next,top,model,btw,gw,gea,dapet,hadiah,te','positif'),
(55,1,'2021-04-09 15:48:40','YUHUUU APA GUE BILANG ILENE BAKAL MENANG?????????????????? @INTM_NET @netmediatama #IleneWinner #IleneOnTheTop #TeamIlene https://t.co/wNLWl5EAXZ','yuhuuu,gue,bilang,ilene,menang','positif'),
(56,1,'2021-04-09 15:45:28','@netmediatama BYE BYE PANAS HAIRDRYER','bye,bye,panas,hairdryer','positif'),
(57,1,'2021-04-09 15:45:13','@grande2002_ @netmediatama @hondaisme Makasii infonya ????','makasii,info','negatif'),
(58,1,'2021-04-09 15:33:36','Kereeennnn bgt parahhhhhh INTM malem final ini sukakkkkk???? @netmediatama','reeennnn,bgt,parahhhhhh,intm,malem,final,sukakkkkk','negatif'),
(59,1,'2021-04-09 15:32:38','@netmediatama Vincent aka Winter Soldier','vincent,aka,winter,soldier','positif'),
(60,1,'2021-04-09 15:32:20','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','positif'),
(61,1,'2021-04-09 15:30:11','Kaan..\nUdah lah bener,, Ilene nih juaranya..\nSesuai dengan penjabaran dan prediksinya twins..@netmediatama #INTMxNet','ka,udah,bener,ilene,nih,juara,suai,penjabaran,prediksi,twins','negatif'),
(62,1,'2021-04-09 15:26:00','#Democrazy\nCC @MataNajwa @KompasTV @tempodotco @tvOneNews @ANTVOfficial_ @TRANS7 @TRANSTV_CORP @CNNIndonesia… https://t.co/l4e6v0M9xR','cc','negatif'),
(63,1,'2021-04-09 15:25:56','ikut deg degan nonton INTM ????\n#TeamIlene @netmediatama https://t.co/xJnB24IYAc','deg,degan,nonton,intm','negatif'),
(64,1,'2021-04-09 15:24:47','Yuhuuu INTM grand final @netmediatama\n#INTMgrandfinal','yuhuuu,intm,grand,final','positif'),
(65,1,'2021-04-09 15:24:33','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/agOtUXSONF','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(66,1,'2021-04-09 15:23:03','@MellowCoolish @netmediatama Dijamin lebih pedes dari deddy cobotak','jamin,pedes,deddy,cobotak','negatif'),
(67,1,'2021-04-09 15:23:00','DEG DEG AN BGT SUMPAH\nDETIK² KEMENANGAN ANTARA GEA OR ILENE????????????\nSIAPA PUN YG BAKAL MENANG INTM C1 INI. KALIAN MEMANG… https://t.co/g7Ja8Qcciw','deg,deg,an,bgt,sumpah,detik,menang,gea,or,ilene,yg,menang,intm,c','negatif'),
(68,1,'2021-04-09 15:22:10','@nasibungkushh @netmediatama Semoga berkah ya pak klo mereka yg jadi','moga,berkah,ya,klo,yg','positif'),
(69,1,'2021-04-09 15:20:48','@netmediatama tolong  siapa  tau dapat dipertimbangkan???? https://t.co/J6X6hldCrR','tolong,tau,timbang','positif'),
(70,1,'2021-04-09 15:18:24','@netmediatama Suka benget sama acara² Net. ... tapi dulu','suka,benget,acara,net','negatif'),
(71,1,'2021-04-09 15:17:13','Sepi ya runawaynya.. #INTMxNET @netmediatama','sepi,ya,runaway','positif'),
(72,1,'2021-04-09 15:12:59','@netmediatama @hondaisme MINNN KENAPA HARUS ADA EFEK EFEK SINETROOONNN, SAYA MAU LIAT NORMAL RUNAWAYYYYYY, AHHH KECEWA','minnn,efek,efek,sinetrooonnn,liat,normal,runawayyyyyy,ahhh,kecewa','negatif'),
(73,1,'2021-04-09 15:12:58','INDONESIA\'S NEXT TOP MODEL KENAPA CAMERA WORK NYA JELEK BENEEEERRRR kek terlalu terdramatisasi jd kek nonton indosi… https://t.co/sYdLF7Rc59','indonesias,next,top,model,camera,work,jelek,beneeeerrrr,kek,terdramatisasi,jd,kek,nonton,indosi','positif'),
(74,1,'2021-04-09 15:03:15','RT @netmediatama: Photoshoot terakhir untuk Top 2 INTM bersama Nicoline Patricia????. Pastinya semakin seru!!\n\nJangan sampai terlambat nonton…','photoshoot,top,intm,nicoline,patricia,pasti,seru,terlambat,nonton','negatif'),
(75,1,'2021-04-09 15:02:13','@Diipsiii @netmediatama Yaaahhh:(','yaaahhh','positif'),
(76,1,'2021-04-09 15:00:49','#TEAMILENE ?????? https://t.co/voh8R3vLco','0','positif'),
(77,1,'2021-04-09 15:00:02','@lialarasmitaa @netmediatama @hondaisme ada','0','negatif'),
(78,1,'2021-04-09 14:55:26','@sytpall @netmediatama Judulnya itu stereo','judul,stereo','positif'),
(79,1,'2021-04-09 14:55:07','@grande2002_ @netmediatama @hondaisme Live stream yt nya ada ?','live,stream,yt','positif'),
(80,1,'2021-04-09 14:55:04','@netmediatama cc: @Standupindo','cc','positif'),
(81,1,'2021-04-09 14:53:55','@netmediatama Pada nanya next, next mah acara ngabuburit haha','na,next,next,mah,acara,ngabuburit,haha','positif'),
(82,1,'2021-04-09 14:53:55','Dukung Film \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung… https://t.co/HChzAGt4L3','dukung,film,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(83,1,'2021-04-09 14:49:52','@lialarasmitaa @netmediatama @hondaisme di yt bisa ka','yt,ka','positif'),
(84,1,'2021-04-09 14:44:08','Harus nonton intm dimana dong aing :( masa di pos ronda @netmediatama','nonton,intm,dimana,aing,pos,ronda','negatif'),
(85,1,'2021-04-09 14:42:55','@netmediatama Rambutnya vincent makin panjang ????????????','rambut,vincent','negatif'),
(86,1,'2021-04-09 14:37:24','@netmediatama @hondaisme Min, kok ga bisa ditonton di https://t.co/CARf8T9vbs yah :( anak kos ga punya tipii','min,ga,tonton,yah,anak,kos,ga,tipi','positif'),
(87,1,'2021-04-09 14:37:23','@MNCPlayID halo ini kok @netmediatama ga bisa ditonton terkait hak siar????!!??','halo,ga,tonton,terkait,hak,siar','positif'),
(88,1,'2021-04-09 14:35:46','@netmediatama Makasih min!','makasih,min','negatif'),
(89,1,'2021-04-09 14:35:31','RT @netmediatama: Frankfurt VS Wolfsburg, Sabtu 10 April 2021 Jam 20.00 WIB #NontonBolaAsiknyadiNET https://t.co/pjoTsdUnC8','frankfurt,vs,wolfsburg,sabtu,april,jam,wib','positif'),
(90,1,'2021-04-09 14:35:14','@arunicanic @netmediatama pinochio udh tapi katanya mimin drama barunya depannya judulnya a','pinochio,udh,mimin,drama,baru,dep,judul,a','negatif'),
(91,1,'2021-04-09 14:34:46','@netmediatama min gantinya depannya judulnya a another miss oh ya min? cefatt spill minn rep88 udh tamat tapi mimin… https://t.co/9z4eXaHkkL','min,ganti,dep,judul,a,another,miss,oh,ya,min,cefatt,spill,minn,rep,udh,tamat,mimin','positif'),
(92,1,'2021-04-09 14:34:38','@netmediatama Film turki tetap tayang kan min?','film,turki,tayang,min','positif'),
(93,1,'2021-04-09 14:34:34','RT @netmediatama: Vincent udah mulai kesel, disuruh main sendiri aja???? https://t.co/U5fB4BdvnW','vincent,udah,kesel,suruh,main,aja','negatif'),
(94,1,'2021-04-09 14:34:25','@netmediatama @hondaisme ILENE TO THE BE ON TOP ???','ilene,to,the,be,on,top','positif'),
(95,1,'2021-04-09 14:34:24','@netmediatama @hondaisme Wohow','wohow','negatif'),
(96,1,'2021-04-09 14:33:29','@netmediatama @hondaisme UDH MANTENGINN INIMINNN','udh,mantenginn,iniminnn','negatif'),
(97,1,'2021-04-09 14:33:20','@netmediatama @hondaisme @R_AninJKT48','0','positif'),
(98,1,'2021-04-09 14:30:52','@AndyArdzh @netmediatama @malam_malamNET Di YouTube','youtube','positif'),
(99,1,'2021-04-09 14:30:00','YUKK NYALAIN TV-NYA SEKARANG! GRAND FINAL INDONESIA\'S NEXT TOP MODEL SUDAH DIMULAI! #INTMXNET ????\n\nDipersembahkan ole… https://t.co/ynrjVYa2YO','yukk,nyalain,tv-,grand,final,indonesias,next,top,model,sembah,ole','negatif'),
(100,1,'2021-04-09 14:29:15','OMG! https://t.co/doQrkEfo3N','omg','negatif'),
(151,2,'2021-04-10 23:57:21','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','positif'),
(152,2,'2021-04-10 23:33:48','RT @AyuIskandar_: Udah gede juga ttep aja gak bisa move on dari film BARBIE soalnya emg seru, skrg juga lagi nonton di @OfficialRCTI #SALAM…','udah,gede,ttep,aja,gak,move,on,film,barbie,emg,seru,skrg,nonton','negatif'),
(153,2,'2021-04-10 23:12:40','@Haruka_NKGW10 @OfficialRCTI Good morning.. https://t.co/6MQ8S2w8j0','good,morning','negatif'),
(154,2,'2021-04-10 22:34:05','@OfficialRCTI Kalo menurut saya film ini harus dihentikan sementara nanti setelah Ramadhan baru tayang LG biar umat muslim fokus keramadhan.','kalo,film,henti,ramadhan,tayang,lg,biar,umat,muslim,fokus,ramadhan','positif'),
(155,2,'2021-04-10 22:30:49','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','negatif'),
(156,2,'2021-04-10 18:32:18','@ShopeeCare @OfficialRCTI @MNC_Pictures buodo amat al andin , kembaliin fitur pengiriman kaya dulu lagi lah , biasa… https://t.co/2EB8cekd8E','buodo,al,andin,mbaliin,fitur,pengiriman,kaya','positif'),
(157,2,'2021-04-10 16:50:35','RT @ShopeeID: Iklan Shopee Big Ramadan Sale Edisi Spesial Ikatan Cinta ini dapat terlaksana berkat kerjasama manis antara Shopee dengan @Of…','iklan,shopee,big,ramadan,sale,edisi,spesial,ikat,cinta,terlaksana,berkat,rjasama,manis,shopee','positif'),
(158,2,'2021-04-10 16:27:34','@ShopeeID @OfficialRCTI @MNC_Pictures Bismillah semoga menang','bismillah,moga,menang','positif'),
(159,2,'2021-04-10 16:27:21','RT @ShopeeID: Iklan Shopee Big Ramadan Sale Edisi Spesial Ikatan Cinta ini dapat terlaksana berkat kerjasama manis antara Shopee dengan @Of…','iklan,shopee,big,ramadan,sale,edisi,spesial,ikat,cinta,terlaksana,berkat,rjasama,manis,shopee','negatif'),
(160,2,'2021-04-10 16:22:27','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','positif'),
(161,2,'2021-04-10 16:20:20','RT @ShopeeID: Iklan Shopee Big Ramadan Sale Edisi Spesial Ikatan Cinta ini dapat terlaksana berkat kerjasama manis antara Shopee dengan @Of…','iklan,shopee,big,ramadan,sale,edisi,spesial,ikat,cinta,terlaksana,berkat,rjasama,manis,shopee','negatif'),
(162,2,'2021-04-10 16:04:49','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','positif'),
(163,2,'2021-04-10 15:56:20','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','positif'),
(164,2,'2021-04-10 15:27:38','RT @ShopeeID: Iklan Shopee Big Ramadan Sale Edisi Spesial Ikatan Cinta ini dapat terlaksana berkat kerjasama manis antara Shopee dengan @Of…','iklan,shopee,big,ramadan,sale,edisi,spesial,ikat,cinta,terlaksana,berkat,rjasama,manis,shopee','negatif'),
(165,2,'2021-04-10 15:01:34','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','negatif'),
(166,2,'2021-04-10 14:54:47','@OfficialRCTI Mereka yg mkan mlm aku yg bucinn\n#IkatanCintaEp233','yg,m,mlm,yg,bucinn','positif'),
(167,2,'2021-04-10 14:45:38','@OfficialRCTI @LayarDrama_RCTI Tentunya... Sekian lama menanti dr jerawatan s/ jerawat pecah &amp; jaDi bisul????','kian,dr,jerawat,s,jerawat,pecah,amp,bisul','positif'),
(168,2,'2021-04-10 14:42:17','@OfficialRCTI @RCTIPlus Jadi aurel itu kakek yg tak mempan disuntik','aurel,kakek,yg,mempan,suntik','positif'),
(169,2,'2021-04-10 14:40:00','Waduh Kok Bisa?! Kakek Ini Tak Mempan Disuntik\n#NewsRCTIPlus @RCTIPlus\nhttps://t.co/ezb5WkWcmU','kakek,mempan,suntik','positif'),
(170,2,'2021-04-10 14:37:01','RT @MylyodraOfc: wahh akan ada kejutan apa lagi yaaa dari kolaborasi @laleilmanino dengan the super girls dalam panggung #IdolRoadToGrandFi…','wahh,jut,yaaa,kolaborasi,the,super,girls,panggung','negatif'),
(171,2,'2021-04-10 14:31:29','Knpa sii klog IC #IkatanCintaEp233 dikit bgt durasinya.. \nPangeran aja lamanya minta ampun ,, jawab plisss ???????? @OfficialRCTI','knpa,si,klog,ic,dikit,bgt,durasi,pangeran,aja,ampun,plisss','positif'),
(172,2,'2021-04-10 14:26:41','@Wanz58311483 @OfficialRCTI Sumpah .. Bener bgt ????','sumpah,bener,bgt','negatif'),
(173,2,'2021-04-10 14:26:24','Ikatan Cinta tanpa kiki dan mirna itu ibarat HAMPA. Gak ada seorang pun yang bisa ngeledekin bosnya sendiri kecuali… https://t.co/jYPECOY1Iu','ikat,cinta,kik,mirna,hampa,gak,ngeledekin,bos,kecuali','positif'),
(174,2,'2021-04-10 14:17:04','Bentaran banget #IkatanCintaEp233 klo sinetron pangeran durasinya lama.. @OfficialRCTI','bentar,banget,klo,sinetron,pangeran,durasi','positif'),
(175,2,'2021-04-10 14:10:00','Jelang Hari Pertama di Bulan Ramadhan Berikut Hal Yang Harus Kamu Persiapkan\n#NewsRCTIPlus @RCTIPlus\nhttps://t.co/h4Te7I8oO5','jelang,ramadhan,persiap','negatif'),
(176,2,'2021-04-10 14:04:26','RT @OfficialRCTI: Memang mereka berdua selalu bisa menyegarkan suasana ???? #IkatanCintaEp233 https://t.co/06e2jKjUff','dua,menyegar,suasana','positif'),
(177,2,'2021-04-10 13:46:48','RT @OfficialRCTI: Memang mereka berdua selalu bisa menyegarkan suasana ???? #IkatanCintaEp233 https://t.co/06e2jKjUff','dua,menyegar,suasana','negatif'),
(178,2,'2021-04-10 13:43:00','RT @OfficialRCTI: Memang mereka berdua selalu bisa menyegarkan suasana ???? #IkatanCintaEp233 https://t.co/06e2jKjUff','dua,menyegar,suasana','negatif'),
(179,2,'2021-04-10 13:42:40','Tumpeng biar syukuran min https://t.co/8eB0NRanqp','tumpeng,biar,syukur,min','positif'),
(180,2,'2021-04-10 13:42:20','RT @OfficialRCTI: Memang mereka berdua selalu bisa menyegarkan suasana ???? #IkatanCintaEp233 https://t.co/06e2jKjUff','dua,menyegar,suasana','positif'),
(181,2,'2021-04-10 13:41:27','Memang mereka berdua selalu bisa menyegarkan suasana ???? #IkatanCintaEp233 https://t.co/06e2jKjUff','dua,menyegar,suasana','negatif'),
(182,2,'2021-04-10 13:40:39','@OfficialRCTI Ga seneng gmna ini yg di tunggu tunggu min????????????','ga,neng,gmna,yg,tunggu,tunggu,min','positif'),
(183,2,'2021-04-10 13:40:00','Gempa Bumi 6,7 M Guncang Malang, Jogja dan Surabaya\n#NewsRCTIPlus @RCTIPlus\nhttps://t.co/nFdxLzHglO','gempa,bumi,m,guncang,malang,jogja,surabaya','positif'),
(184,2,'2021-04-10 13:39:36','Okemin nontonnya sedang kerja atau dirumah nuih whahah https://t.co/mIOv1aKa5e','okemin,nonton,kerja,rumah,nuih,whahah','negatif'),
(185,2,'2021-04-10 13:36:03','@OfficialRCTI Keringggg gigi saya minnn','ringggg,gigi,minnn','positif'),
(186,2,'2021-04-10 13:36:00','@OfficialRCTI malem minggu di kasih asupan kaya gini seneng banget min','malem,minggu,kasih,asupan,kaya,gin,neng,banget,min','positif'),
(187,2,'2021-04-10 13:35:17','@OfficialRCTI #IkatanCintaEp233','0','negatif'),
(188,2,'2021-04-10 13:35:03','@OfficialRCTI Karena hilal Aladin sudah dekat ????','hilal,aladin','positif'),
(189,2,'2021-04-10 13:35:02','@OfficialRCTI Biasalaaaaah... ????','biasalaaaaah','positif'),
(190,2,'2021-04-10 13:34:41','@OfficialRCTI Soo sweet bangettt gak tau lagi sama Aladin sumringaaa sendiri gue lihatnya sampe jingkrak-jingkrak m… https://t.co/ef6Jv6RnBE','soo,sweet,bangettt,gak,tau,aladin,sumringaaa,gue,lihat,sampe,jingkrak-jingkrak,m','negatif'),
(191,2,'2021-04-10 13:34:40','@OfficialRCTI Gue senyum-senyum sendiri min wkwkw','gue,nyum-senyum,min,wkwkw','negatif'),
(192,2,'2021-04-10 13:32:39','Mereka yang honeymoon, warga yang ikut seneng ????#IkatanCintaEp233','honeymoon,warga,neng','positif'),
(193,2,'2021-04-10 13:27:25','RT @MylyodraOfc: wahh akan ada kejutan apa lagi yaaa dari kolaborasi @laleilmanino dengan the super girls dalam panggung #IdolRoadToGrandFi…','wahh,jut,yaaa,kolaborasi,the,super,girls,panggung','negatif'),
(194,2,'2021-04-10 13:23:15','wahh akan ada kejutan apa lagi yaaa dari kolaborasi @laleilmanino dengan the super girls dalam panggung… https://t.co/cHkAN4TA9u','wahh,jut,yaaa,kolaborasi,the,super,girls,panggung','negatif'),
(195,2,'2021-04-10 13:10:00','Video Bunga Citra Lestari Merangkul Ariel Noah Bocor\n#NewsRCTIPlus @RCTIPlus\nhttps://t.co/zeEkbRlByY','video,bunga,citra,lestari,merangkul,ariel,noah,bocor','positif'),
(196,2,'2021-04-10 13:00:57','@bankocbcnisp @OfficialRCTI Selamat malam. Ka, atm ayah saya tertinggal di mesin atm lalu hilang sore ini. Bagaiman… https://t.co/mEt8Ql2WDv','selamat,malam,ka,atm,ayah,tertinggal,mesin,atm,hilang,sore,bagaiman','negatif'),
(197,2,'2021-04-10 12:55:12','RT @susanlie91: #Agnation #iHeartAwards #BestFanArmy \n\nRT @OfficialRCTI: Tebak, @agnezmo nyanyi lagu apa? Cantik banget Queen ????\n\n# Indonesi…','rt,tebak,nyanyi,lagu,cantik,banget,queen,indonesi','negatif'),
(198,2,'2021-04-10 12:47:47','@ShopeeID @OfficialRCTI @MNC_Pictures Done ikutan share #IKATANCINTASHOPEE','done,ikut,share','positif'),
(199,2,'2021-04-10 12:47:19','RT @ShopeeID: Iklan Shopee Big Ramadan Sale Edisi Spesial Ikatan Cinta ini dapat terlaksana berkat kerjasama manis antara Shopee dengan @Of…','iklan,shopee,big,ramadan,sale,edisi,spesial,ikat,cinta,terlaksana,berkat,rjasama,manis,shopee','positif'),
(200,2,'2021-04-10 12:45:03','Surprise dari Mama Rosa, Miss Kiki dan Ncus Mirna sepertinya berhasil nih!?\n\nSaksikan #IkatanCintaRCTI MALAM INI pu… https://t.co/dUK35Q9AkQ','surprise,mama,rosa,miss,kik,ncus,mirna,hasil,nih,saksi,malam,pu','negatif'),
(201,2,'2021-04-10 12:43:58','Wah Rohmat balik ke pasar Makmur, apa keputusan yang diambil sudah sesuai?\n\nSaksikan #AmanahWali4RCTI MALAM INI puk… https://t.co/nlYGhzdOsj','rohmat,pasar,makmur,putus,ambil,suai,saksi,malam,puk','negatif'),
(202,2,'2021-04-10 12:43:57','@ShopeeCare @OfficialRCTI @MNC_Pictures Min cek DM dong, shopee express lama banget','min,cek,dm,shopee,express,banget','negatif'),
(203,2,'2021-04-10 12:43:47','Hayooo para ciwii bener gak sih kalian kaya gini? ????\n\nEh btw @skyskuuy_ cocok juga yaa kaya gitu ????\n\nStreaming Sumber… https://t.co/wKFgot3Jy1','hayooo,ciwii,bener,gak,sih,kaya,gin,eh,btw,cocok,yaa,kaya,gitu,streaming,sumber','negatif'),
(204,2,'2021-04-10 12:42:40','Top-up Rp50ribu buat dapetin EXTRA bonus Paket Juara/GOL07 selama 30 hari atau Top-up Rp130ribu buat dapetin EXTRA… https://t.co/D8OZdDRnqF','top-up,rpribu,dapetin,extra,bonus,paket,juaragol,top-up,rpribu,dapetin,extra','positif'),
(205,2,'2021-04-10 12:41:48','Program ini juga dapat kamu saksikan melalui aplikasi @rctiplusofficial\n.\n#GTV #bagibagibahagiagtv… https://t.co/WkJe7txcx9','program,saksi,aplikasi','negatif'),
(206,2,'2021-04-10 12:41:47','Masihkah kalian ragu untuk meminta maaf kepada orang tua?\n.\nSaksikan  Aku Ingin Pulang, bersama @fannyghassani seti… https://t.co/clE7jLu84r','ragu,maaf,orang,tua,saksi,pulang,seti','positif'),
(207,2,'2021-04-10 12:40:58','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','negatif'),
(208,2,'2021-04-10 12:40:31','RT @IndonesianIdol: Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga dar…','get,ready,for,penampilan,finalis,top,special,collaboration,dar','negatif'),
(209,2,'2021-04-10 12:40:28','...Periode program mulai dari tanggal 12 Maret 2021 (06.00 WIB) sampai dengan 11 April 2021 (23.59 WIB), selama per… https://t.co/jNn9iFKzJ2','periode,program,tanggal,maret,wib,april,wib','negatif'),
(210,2,'2021-04-10 12:40:27','Hey kamu! Dapatkan kesempatan mendapat saldo gratis 50 ribu Rupiah dari SPIN Pay!\n\nSPIN Pay bagi-bagi saldo gratis… https://t.co/UcX6uNakyb','hey,dapat,sempat,saldo,gratis,ribu,rupiah,spin,pay,spin,pay,bagi-bagi,saldo,gratis','negatif'),
(211,2,'2021-04-10 12:40:09','@OfficialRCTI hei,  Sutradara,  harusnya Nawang dan Purtri ganti nomor dong hadeuh..\nMenyebalkan','hei,sutradara,nawang,purtri,ganti,nomor,hadeuh,menyebal','negatif'),
(212,2,'2021-04-10 12:40:00','Muncul Perempuan Dalam Instastory Niko Al Hakim, Penyebab Perceraiannya Dengan Rachel Vennya?\n#NewsRCTIPlus… https://t.co/vPf020OixA','muncul,perempuan,instastory,niko,al,hakim,penyebab,perceraian,rachel,ven','negatif'),
(213,2,'2021-04-10 12:39:12','Get ready for #IdolRoadToGrandFinal ????\nSelain ada penampilan dari finalis TOP 3, akan ada Special Collaboration juga… https://t.co/769ivOqL3l','get,ready,for,penampilan,finalis,top,special,collaboration','positif'),
(214,2,'2021-04-10 12:38:30','... Cek detailnya yuk di https://t.co/lDDmzU0khq / download langsung aplikasinya di IOS &amp; PlayStore \n\n#blanjadiemshop #lowcarboricecooker','cek,detail,yuk,download,langsung,aplikasi,ios,amp,playstore','positif'),
(215,2,'2021-04-10 12:38:29','...Rice Cooker Low Carbo DR Duck bosa mengurangi kadar gula pd beras yg km masak sehingga km ga perlu lagi deh khaw… https://t.co/dQFJhEE0qn','rice,cooker,low,carbo,dr,duck,bosa,mengurangi,kadar,gula,pd,beras,yg,km,masak,km,ga,deh,khaw','positif'),
(216,2,'2021-04-10 12:38:28','Halo semuaaa.. Buat kamu yang pengen banget makan nasi tapi takut gemuk, sekarang gak perlu khawatir!! ????\n\nProduk te… https://t.co/WiEGV22Ttf','halo,muaaa,pengen,banget,makan,nasi,takut,gemuk,gak,khawatir,produk,te','positif'),
(217,2,'2021-04-10 12:36:38','Show Your Talent Season 2 has finally begun. Create your most interesting talent video and win a total prize of IDR… https://t.co/Ajd9UOBvzy','show,your,talent,ason,has,finally,begun,create,your,most,interesting,talent,video,and,win,a,total,prize,of,idr','negatif'),
(218,2,'2021-04-10 12:36:36','@OfficialRCTI Berhentilah &amp; Ini Peringatan Yg Terakhir Kalinya.!!!\n\nKau Mengganggu Hpku ????','henti,amp,peringatan,yg,kal,kau,mengganggu,hp','negatif'),
(219,2,'2021-04-10 12:34:50','...Cara pengundian pemenang:\nSetiap pendaftar baru HARIO kelipatan 20 di dalam sistem, mendapatkan E Saldo SPIN seb… https://t.co/kXMbzdRKIO','pengundian,pemenang,pendaftar,hario,lipat,sistem,e,saldo,spin,b','positif'),
(220,2,'2021-04-10 12:34:49','GIVEAWAY TIME!!\nHari gini siapa yg gak mau ESaldo SPIN? Mulai dr beli pulsa listrik, sampe Game Voucher semua bisa… https://t.co/vKbGbpeAbY','giveaway,time,gin,yg,gak,esaldo,spin,dr,beli,pulsa,listrik,sampe,game,voucher','positif'),
(221,2,'2021-04-10 12:33:10','April, ajuin Kartu Kredit MNC Bank &amp; dpt BEBAS IURAN tahunan 2 thn pertama.\nPakai aplikasi MOTION utk kemudahan trx… https://t.co/gwTrXSImMu','april,ajuin,kartu,kredit,mnc,bank,amp,dpt,bebas,iur,tahun,thn,pakai,aplikasi,motion,utk,mudah,trx','positif'),
(222,2,'2021-04-10 12:32:07','...Hub1500188/ https://t.co/CYeSvhpBUP\n \n#MOTION #FutureBankingHere dari #MNCBank','hub','negatif'),
(223,2,'2021-04-10 12:32:07','Pemegang baru Kartu Kredit MNC Bank cukup pakai MOTION apps utk aktivasi kartu, pilih menu credit card &amp; ikuti lang… https://t.co/KfyWMScWwV','pemegang,kartu,kredit,mnc,bank,pakai,motion,apps,utk,aktivasi,kartu,pilih,menu,credit,card,amp,ikut,lang','positif'),
(224,2,'2021-04-10 11:23:31','RT @OfficialRCTI: Surprise dari Mama Rosa, Miss Kiki dan Ncus Mirna sepertinya berhasil nih?\n\nWah #AladinOnTheWay akan segera, OkeMin jadi…','surprise,mama,rosa,miss,kik,ncus,mirna,hasil,nih,okemin','negatif'),
(225,2,'2021-04-10 11:21:01','RT @OfficialRCTI: Ada yang makin perhatian. Ada yang setia menyemangati ?? #IkatanCintaEp232 https://t.co/GNhONynbZ5','perhatian,setia,menyemangati','negatif'),
(226,2,'2021-04-10 11:13:35','@OfficialRCTI Kan ibu Nawang sudah nikah sama pak Raymond,  ya sudah mereka bahagia,  ga perlu ada gangguan lagi,… https://t.co/tDelzaN0Lh','nawang,nikah,raymond,ya,bahagia,ga,ganggu','positif'),
(227,2,'2021-04-10 11:03:22','@OfficialRCTI kenapa min puasa ga nyiarin serie A?? Aneh padahal seru lagi sahur sambil nonton bola....','min,puasa,ga,nyiarin,rie,a,aneh,seru,sahur,nonton,bola','positif'),
(228,2,'2021-04-10 10:57:12','@OfficialRCTI mending ceritanya tentang  Mel,  RisKy,  Tristan. Maura Pangeran,  Putri dan Arga, \nGak ush pakai aca… https://t.co/BDdHd4pSaV','mending,cerita,mel,risky,tristan,maura,pangeran,putri,arga,gak,ush,pakai,aca','negatif'),
(229,2,'2021-04-10 10:31:37','@OfficialRCTI malas nonton sinetron ini,  apalagi oeran Ranti jadi putri,  koq kepala batu,  dan ngeyel, katanya ba… https://t.co/YeuoH4R6uQ','malas,nonton,sinetron,oeran,ranti,putri,koq,kepala,batu,ngeyel,ba','negatif'),
(230,2,'2021-04-10 10:14:27','Dari Cinta Lokasi, Beberapa Pasangan Dapat Menjadi Serasi dan Awet. ???? https://t.co/ovzJhHVLux\n\n#AdaRadioPlus','cinta,lokasi,pasang,serasi,awet','positif'),
(231,2,'2021-04-10 09:57:30','@ShopeeCare @OfficialRCTI @MNC_Pictures Min minta no tlp/wa kurir shopee express donk. Paketku status sedang dikiri… https://t.co/qIC4VpkicO','min,no,tlpwa,kurir,shopee,express,donk,paket,status,kiri','negatif'),
(232,2,'2021-04-10 09:57:25','RT @drg_ester: #Records @drg_ester from Lembaga #Prestasi #Indonesia+#Dunia/CEO #PaulusPangkaSH;on @OfficialRCTI after Pres.election http:/…','from,lembaga,ceo,on,after,preselection,http','positif'),
(233,2,'2021-04-10 09:48:53','Besok, 11 April 2021 jam 19:00 WIB di @officialRCTI, kamu bisa nonton drama musikal finansial pertama di Indonesia… https://t.co/I46CG68jYw','besok,april,jam,wib,nonton,drama,musikal,finansial,indonesia','positif'),
(234,2,'2021-04-10 09:47:32','RT @OfficialRCTI: Waduh, bang Ojak cuma anggap Sasi sebagai adik?\n\nLalu gimana nih perjuangan cinta Ojak, apa bakal jatuh ke mpok Uyuy?\n\nSa…','bang,ojak,anggap,sasi,adik,gimana,nih,perjuangan,cinta,ojak,jatuh,mpok,uyuy,sa','negatif'),
(235,2,'2021-04-10 09:47:24','RT @OfficialRCTI: Ibu Nawang ke makam bayinya?\nSementara Pangeran tetap saja melindungi Putri dan Ibu Nawang dari kejahatan Lisa!? Apakah L…','nawang,makam,bayi,pangeran,melindungi,putri,nawang,jahat,lisa,l','positif'),
(236,2,'2021-04-10 09:47:20','RT @OfficialRCTI: Surprise dari Mama Rosa, Miss Kiki dan Ncus Mirna sepertinya berhasil nih?\n\nWah #AladinOnTheWay akan segera, OkeMin jadi…','surprise,mama,rosa,miss,kik,ncus,mirna,hasil,nih,okemin','positif'),
(237,2,'2021-04-10 09:46:56','RT @OfficialRCTI: Bu Ines telfon kang Aceng? Tapi kang Aceng bilang “Juga kangen sama dia..” tapi Akum tegaskan ‘Dianya bu Ines atau Entin?…','bu,ines,telfon,kang,aceng,kang,aceng,bilang,kangen,akum,tegas,a,bu,ines,entin','negatif'),
(238,2,'2021-04-10 09:46:13','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(239,2,'2021-04-10 09:46:07','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','negatif'),
(240,2,'2021-04-10 09:46:04','RT @bsatriagaruda: Hallo Guys, Mau Masker Ekslusif BIMA S?!\n\nCaranya gampang banget loh, kamu tinggal nonton \"BIMA S\" saat tayangan sedang…','hallo,guys,masker,ekslusif,bima,s,gampang,banget,loh,tinggal,nonton,bima,s,tayang','positif'),
(241,2,'2021-04-10 09:46:01','RT @bsatriagaruda: Mulai Minggu, 11 April 2021 \"BIMA S\" siap dengan \"EPISODE BARUNYA\" jam 10.00 WIB di @OfficialRCTI ????\n.\nJangan lewatkan ya…','minggu,april,bima,s,episode,baru,jam,wib,lewat,ya','positif'),
(242,2,'2021-04-10 09:45:54','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(243,2,'2021-04-10 09:45:48','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','negatif'),
(244,2,'2021-04-10 09:45:45','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','negatif'),
(245,2,'2021-04-10 09:45:41','RT @bsatriagaruda: Hallo Guys, Mau Masker Ekslusif BIMA S?!\n\nCaranya gampang banget loh, kamu tinggal nonton \"BIMA S\" saat tayangan sedang…','hallo,guys,masker,ekslusif,bima,s,gampang,banget,loh,tinggal,nonton,bima,s,tayang','positif'),
(246,2,'2021-04-10 09:45:38','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(247,2,'2021-04-10 09:45:34','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(248,2,'2021-04-10 09:45:30','RT @bsatriagaruda: Hallo Guys, Mau Masker Ekslusif BIMA S?!\n\nCaranya gampang banget loh, kamu tinggal nonton \"BIMA S\" saat tayangan sedang…','hallo,guys,masker,ekslusif,bima,s,gampang,banget,loh,tinggal,nonton,bima,s,tayang','positif'),
(249,2,'2021-04-10 09:45:22','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(250,2,'2021-04-10 09:45:17','RT @bsatriagaruda: New Episode BIMA S “The Seven Waterfalls” Mulai Minggu, 11 April 2021 Jam 10.00 WIB Hanya di @OfficialRCTI\n \n#NewEpisode…','new,episode,bima,s,the,ven,waterfalls,minggu,april,jam,wib','positif'),
(251,2,'2021-04-10 09:45:07','RT @bsatriagaruda: Hallo Guys, Mau Masker Ekslusif BIMA S?!\n\nCaranya gampang banget loh, kamu tinggal nonton \"BIMA S\" saat tayangan sedang…','hallo,guys,masker,ekslusif,bima,s,gampang,banget,loh,tinggal,nonton,bima,s,tayang','negatif'),
(252,2,'2021-04-10 09:45:04','RT @OfficialRCTI: “Perbesar bisnis, perbanyak keuntungannya...”\n\nNgga sabar untuk nonton #PremanPensiun5?\n\nStandby di timeline OkeMin &amp; @La…','perbesar,bisnis,perbanyak,untung,ngga,sabar,nonton,standby,timeline,okemin,amp','negatif'),
(253,2,'2021-04-10 09:36:51','RT @tikachhuw: Lengkap nya kalian bisa tonton di Oke Chef ???? @OfficialRCTI https://t.co/Yxok7dbPGb','lengkap,tonton,oke,chef','negatif'),
(254,2,'2021-04-10 09:35:26','Kawula Muda, besok (11/4/21) jam 19:00 WIB di @officialRCTI, kamu bisa nonton drama musikal finansial pertama di In… https://t.co/CT0Xa97DOJ','kawula,muda,besok,jam,wib,nonton,drama,musikal,finansial,in','negatif'),
(255,2,'2021-04-10 09:32:51','@ShopeeCare @OfficialRCTI @MNC_Pictures Kak mau tanya. Menu pulsa dn tagihan kok tdk bisa di buka sdh 4x24 jm. Knpa kak','kak,menu,pulsa,dn,tagih,tdk,buka,sdh,x,jm,knpa,kak','negatif'),
(256,2,'2021-04-10 09:26:07','@SiaranBolaLive @OfficialRCTI gak nyiarin nih?','gak,nyiarin,nih','positif'),
(257,2,'2021-04-10 09:24:56','Surprise dari Mama Rosa, Miss Kiki dan Ncus Mirna sepertinya berhasil nih!?\n\nSaksikan #IkatanCintaRCTI MALAM INI pu… https://t.co/SwMRgUYVlr','surprise,mama,rosa,miss,kik,ncus,mirna,hasil,nih,saksi,malam,pu','positif'),
(258,2,'2021-04-10 09:21:51','Dengerin Kumpulan Lagu Lagu Dipha Barus Yang Akan Menemani Hari Kalian. ???? https://t.co/bawWmwGqNv\n\n#AdaRadioPlus','dengerin,kumpul,lagu,lagu,pha,barus,menemani','negatif'),
(259,2,'2021-04-10 08:46:45','Ayam Geprek Bisnis Baru Si Surti. ???? https://t.co/wCl14AnX7T\n\n#AdaRadioPlus','ayam,geprek,bisnis,si,surti','positif'),
(260,2,'2021-04-10 08:40:10','Program ini dapat kalian saksikan secara streaming di RCTI+ ????????https://t.co/L1sidMB5bh\n\nSurprise dari Mama Rosa, Mis… https://t.co/gawGD03RLe','program,saksi,streaming,rcti,surprise,mama,rosa,mis','negatif'),
(261,2,'2021-04-10 08:38:14','@ShopeeCare @OfficialRCTI @MNC_Pictures Paket mana taiii','paket,taiii','negatif'),
(262,2,'2021-04-10 08:15:00','Berbagai Macam Jenis Tanaman yang Bisa Hilangin Racun. ???? https://t.co/FbkImyzEzj\n\n#AdaRadioPlus','jenis,tanam,hilangin,racun','negatif'),
(263,2,'2021-04-10 08:04:35','@bsatriagaruda @OfficialRCTI maskernya ngga sesuai bentuk helmnya. yg harusnya di jidat jadi di mulut.','masker,ngga,suai,bentuk,helm,yg,jidat,mulut','positif'),
(264,2,'2021-04-10 07:48:43','@arlinatama saat mnc punya hotel sendiri yg bisa mereka manfaatkan dan masih di area bogor juga ???? @LayarDrama_RCTI… https://t.co/w0v6yiXFk2','mnc,hotel,yg,manfaat,area,bogor','negatif'),
(265,2,'2021-04-10 07:46:46','Misteri 20 Noni Belanda yang Masih Menjadi Penunggu Lawang Sewu. ???? https://t.co/qnyCbxkbz2\n\n#AdaRadioPlus','misteri,noni,belanda,penunggu,lawang,sewu','positif'),
(266,2,'2021-04-10 07:19:22','RT @OfficialRCTI: Geseeer! Siap-siap puasa, siap-siap pantengin program spesial #RCTI, yuk! Karna mulai dari sahur sampai setelah tarawih,…','geseeer,siap-siap,puasa,siap-siap,pantengin,program,spesial,yuk,karna,sahur,tarawih','negatif'),
(267,2,'2021-04-10 07:15:00','Ayo Mainkan Game Sudo Indonesia Hanya Di Aplikasi RCTI+. ???? https://t.co/9gnJB3V1aO\n\n#RCTIPlusAdaGame','ayo,main,game,sudo,indonesia,aplikasi,rcti','positif'),
(268,2,'2021-04-10 07:10:00','5 Koleksi Sandal Via Vallen Yang Totalnya Bisa Buat Beli Mobil Bekas Puluhan Juta!\n#NewsRCTIPlus @RCTIPlus\nhttps://t.co/fRqebESXYu','koleksi,sandal,via,vallen,total,beli,mobil,bekas,puluh,juta','negatif'),
(269,2,'2021-04-10 07:07:37','Siap-siap ya. Upload foto selfie kamu dengan karakter \"BIMA S\" lalu tag ke @officialrcti &amp; Bima S Animation ya, ser… https://t.co/CoowUOl4Fk','siap-siap,ya,upload,foto,lfie,karakter,bima,s,tag,amp,bima,s,animation,ya,r','positif'),
(270,2,'2021-04-10 07:07:33','@OfficialRCTI Ga mau berharaplah.. Takut kena prank...','ga,harap,takut,kena,prank','negatif'),
(271,2,'2021-04-10 07:05:30','Wah Rohmat balik ke pasar Makmur, apa keputusan yang diambil sudah sesuai?\n\nSaksikan #AmanahWali4RCTI MALAM INI puk… https://t.co/43L9WdntgH','rohmat,pasar,makmur,putus,ambil,suai,saksi,malam,puk','negatif'),
(272,2,'2021-04-10 07:04:50','Surprise dari Mama Rosa, Miss Kiki dan Ncus Mirna sepertinya berhasil nih!?\n\nSaksikan #IkatanCintaRCTI MALAM INI pu… https://t.co/jZWHxEKkRX','surprise,mama,rosa,miss,kik,ncus,mirna,hasil,nih,saksi,malam,pu','negatif'),
(273,2,'2021-04-10 07:01:35','RT @OfficialRCTI: “Perbesar bisnis, perbanyak keuntungannya...”\n\nNgga sabar untuk nonton #PremanPensiun5?\n\nStandby di timeline OkeMin &amp; @La…','perbesar,bisnis,perbanyak,untung,ngga,sabar,nonton,standby,timeline,okemin,amp','negatif'),
(274,3,'2021-04-10 23:38:21','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(275,3,'2021-04-10 23:24:31','RT @Doug_Tilley: - The 1990 NIGHT OF THE LIVING DEAD remake. It\'s good!\n- Two full seasons of THE PARTRIDGE FAMLY, for some reason!\n- Sesam…','-,the,night,of,the,living,dead,remake,its,good,-,two,full,asons,of,the,partridge,famly,for,some,reason,-,sesam','positif'),
(276,3,'2021-04-10 23:17:43','@SCTV Samudra....','samudra','negatif'),
(277,3,'2021-04-10 23:14:03','RT @SCTV: MnG kali ini super berbeda seperti biasanya, lho! Karena kali ini kehadiran fans-fans dari #BukuHarianSeorangIstri ke lokasi syut…','mng,kali,super,beda,lho,kali,hadir,fans-fans,lokasi,syut','negatif'),
(278,3,'2021-04-10 23:10:36','[SCHEDULE] JKT48 at Tolak Angin Karnaval 2014 | 15 Februari 2014 | 20.00 | Live On SCTV','schedule,jkt,at,tolak,angin,karnaval,februari,live,on,sctv','negatif'),
(279,3,'2021-04-10 22:59:28','pessoas reclamando da sctv me dá saudade de viçosa','pessoas,reclamando,da,sctv,me,d,saudade,de,viosa','negatif'),
(280,3,'2021-04-10 22:59:11','RT @Doug_Tilley: - The 1990 NIGHT OF THE LIVING DEAD remake. It\'s good!\n- Two full seasons of THE PARTRIDGE FAMLY, for some reason!\n- Sesam…','-,the,night,of,the,living,dead,remake,its,good,-,two,full,asons,of,the,partridge,famly,for,some,reason,-,sesam','positif'),
(281,3,'2021-04-10 22:58:00','@ISUCYfred The SCTV skits were so cute','the,sctv,skits,were,so,cute','negatif'),
(282,3,'2021-04-10 22:57:12','@incognito_nunya I loved the movie, but their segments on SCTV were better.','i,loved,the,movie,but,their,gments,on,sctv,were,better','negatif'),
(283,3,'2021-04-10 22:31:08','@susieq2457 https://t.co/ywQU64n3RO.    SCTV parody of Captain Kangaroo, priceless.','sctv,parody,of,captain,kangaroo,priceless','negatif'),
(284,3,'2021-04-10 22:18:12','- The 1990 NIGHT OF THE LIVING DEAD remake. It\'s good!\n- Two full seasons of THE PARTRIDGE FAMLY, for some reason!… https://t.co/xGKCRT81MO','-,the,night,of,the,living,dead,remake,its,good,-,two,full,asons,of,the,partridge,famly,for,some,reason','positif'),
(285,3,'2021-04-10 21:55:46','@CherryWanders Maybe more than quirky, I recently discovered Welcome to Night Vale. Still trying to figure it out.… https://t.co/z9cssUkCRk','maybe,more,than,quirky,i,recently,scovered,welcome,to,night,vale,still,trying,to,figure,it,out','negatif'),
(286,3,'2021-04-10 21:49:46','@FKARIN3 @SCTV Mending FTVnya.. 2 jam langsung tamat, gk bikin penasaran','mending,ftv,jam,langsung,tamat,gk,bikin,penasaran','positif'),
(287,3,'2021-04-10 21:36:00','Canadians ???????? be like \"Yes, SCTV was on the air!\" https://t.co/b6Fjd9vGPh','canadians,be,like,yes,sctv,was,on,the,air','negatif'),
(288,3,'2021-04-10 21:23:19','Haii SCTV_ InboxSCTV_ ajak ceceh mi_ChristyChiBi ngehost lagi dong, psti bakal lbih seru. Hubungi CP : arie_hamtonyahoo.com','hai,sctv,inboxsctv,ajak,ceceh,michristychibi,ngehost,psti,lbih,seru,hubung,cp,ariehamtonyahoocom','positif'),
(289,3,'2021-04-10 21:19:59','@ilihcil Bikin sinetron sctv abisini','bikin,sinetron,sctv,abisini','positif'),
(290,3,'2021-04-10 21:00:57','@xhoxholates @K_DramaIndo Ttapi kalo di sctv kan pake dijelasin komposisi, manfaat, tempat belinya juga, alias ngiklannya luamaaa euyyy','ttapi,kalo,sctv,pake,jelasin,komposisi,manfaat,bel,alias,ngiklan,luamaaa,euyyy','negatif'),
(291,3,'2021-04-10 20:56:46','Ada lorong waktu jam segini di sctv?','lorong,jam,gin,sctv','negatif'),
(292,3,'2021-04-10 20:21:49','Haii SCTV_ DDSDiamDiamSuka ajak ceceh mi_ChristyChiBi main jg dong di DDS, psti bakal lbih seru. Hubungi CP : arie_hamtonyahoo.com ^^','hai,sctv,ddsdiamdiamsuka,ajak,ceceh,michristychibi,main,jg,dds,psti,lbih,seru,hubung,cp,ariehamtonyahoocom','positif'),
(293,3,'2021-04-10 20:11:33','officialJKT48 SCTV_ #SMA7 JKT48 - Dirimu Melody #VoteSMA2018','officialjkt,sctv,jkt,-,ri,melody','negatif'),
(294,3,'2021-04-10 20:11:00','Rindu pamas,nak. #mapy #pamas #aina #janee #antafarastory @ SCTV Tower https://t.co/Hxfvu7usGa','rindu,pamasnak,sctv,tower','positif'),
(295,3,'2021-04-10 19:49:43','Haii SCTV_ FTV_SCTV ajak ceceh mi_ChristyChiBi main di FTV dong, psti bakal lbih seru. Hubungi CP : arie_hamtonyahoo.com','hai,sctv,ftvsctv,ajak,ceceh,michristychibi,main,ftv,psti,lbih,seru,hubung,cp,ariehamtonyahoocom','positif'),
(296,3,'2021-04-10 19:23:49','@bambangismoyo_ yg lain jg gada yg menarik, ucl udh ada di sctv pula wkwk','yg,jg,gada,yg,menarik,ucl,udh,sctv,wkwk','positif'),
(297,3,'2021-04-10 19:10:51','Sambalado, Vokal: Ahmadhusein5+Ayu tingting https://t.co/SBv2F1vJBt via @YouTube https://t.co/pc9TkDACdn,… https://t.co/67Dtr2BiV7','sambalado,vokal,ahmadhuseinayu,tingting,via','positif'),
(298,3,'2021-04-10 19:08:24','@JAFOOFAJ That was us too. We are big Eugene Levy/Catherine O\'Hara fans from SCTV, tried the first episode of Schit… https://t.co/FTm3V6MCk5','that,was,us,too,we,are,big,eugene,levycatherine,ohara,fans,from,sctv,tried,the,first,episode,of,schit','negatif'),
(299,3,'2021-04-10 19:07:52','Se a querida sctv me permitir eu queria ver o jogo sabe','a,querida,sctv,me,permitir,eu,queria,ver,o,jogo,sabe','positif'),
(300,3,'2021-04-10 19:07:19','@mingiku jodohku anak juragan belut saksikan pukul 13:00 wib hanya di sctv satu untuk semua','jodoh,anak,juragan,belut,saksi,wib,sctv','negatif'),
(301,3,'2021-04-10 19:00:18','@DimasLinggan D sctv lain euy?','d,sctv,euy','negatif'),
(302,3,'2021-04-10 18:39:14','@sagipeeps sctv','sctv','positif'),
(303,3,'2021-04-10 18:30:30','@AnthonyDeVito @MelFreelance I MISS #SCTV so much!  And #OnTheTelevision','i,miss,so,much,and','negatif'),
(304,3,'2021-04-10 18:18:58','@Indosiar @SCTVSports Min, SCTV gak ambil el classico malam ini?','min,sctv,gak,ambil,el,classico,malam','positif'),
(305,3,'2021-04-10 18:12:53','wlaupun sctv lg seru, tp gwe milih masuk kamar, serem fren di ruang tamu jam segini','wlau,sctv,lg,seru,tp,gwe,milih,masuk,kamar,rem,fren,ruang,tamu,jam,gin','positif'),
(306,3,'2021-04-10 18:12:51','@pat_oates @FatActionFigure SCTV and Not Nine O’Clock News are both good sketch comedy palette cleansers after atte… https://t.co/wHnmweIHJg','sctv,and,not,nine,oclock,news,are,both,good,sketch,comedy,palette,cleansers,after,atte','negatif'),
(307,3,'2021-04-10 18:11:38','@PLUMBER822 @s3rah_kamu_aja Klo d SCTV gk tayang coba di Bein plum','klo,d,sctv,gk,tayang,coba,bein,plum','positif'),
(308,3,'2021-04-10 18:05:38','@s3rah_kamu_aja @SyndicateBarbar Aku lagi nungguin el clasico nihhh...tayang gak ya SCTV..?','nungguin,el,clasico,nihhhtayang,gak,ya,sctv','negatif'),
(309,3,'2021-04-10 18:02:15','SINETRON SCTV JAM JAM SEGINI TUH SERU SERU NJIR????????????','sinetron,sctv,jam,jam,gin,tuh,seru,seru,njir','positif'),
(310,3,'2021-04-10 17:56:11','@chadmcwin @FatActionFigure I think John Candys best work was on SCTV','i,think,john,candys,best,work,was,on,sctv','negatif'),
(311,3,'2021-04-10 17:53:15','@FatActionFigure @pat_oates Have you seen John Candy play drunkard Orson Wells on SCTV.\nWith the beard, I imagine i… https://t.co/CGlfBGpkSF','have,you,en,john,candy,play,drunkard,orson,wells,on,sctv,with,the,beard,i,imagine,i','negatif'),
(312,3,'2021-04-10 17:49:13','Haii SCTV_ INBOXSCTV_ ajak ceceh mi_ChristyChiBi ngehost lagi dong, psti bakal lbih seru. Hubungi CP : arie_hamtonyahoo.com','hai,sctv,inboxsctv,ajak,ceceh,michristychibi,ngehost,psti,lbih,seru,hubung,cp,ariehamtonyahoocom','positif'),
(313,3,'2021-04-10 17:40:47','Cantik sih tapi sayang\n\"SCTV\"','cantik,sih,sayang,sctv','positif'),
(314,3,'2021-04-10 17:35:04','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','negatif'),
(315,3,'2021-04-10 17:30:33','officialJKT48 SCTV_ #SMA9 JKT48 - Dirimu Melody #VoteSMA2018','officialjkt,sctv,jkt,-,ri,melody','positif'),
(316,3,'2021-04-10 17:23:07','aku honda,kamu sctv','hondaka,sctv','positif'),
(317,3,'2021-04-10 17:19:56','Haii SCTV_ DDSDiamDiamSuka ajak ceceh mi_ChristyChiBi main jg dong di DDS, psti bakal lbih seru. Hubungi CP : arie_hamtonyahoo.com ^^','hai,sctv,ddsdiamdiamsuka,ajak,ceceh,michristychibi,main,jg,dds,psti,lbih,seru,hubung,cp,ariehamtonyahoocom','positif'),
(318,3,'2021-04-10 17:18:59','@chertky I thought maybe I had tuned into SCTV not CPAC.','i,thought,maybe,i,had,tuned,into,sctv,not,cpac','negatif'),
(319,3,'2021-04-10 17:10:29','Cantik sih tapi Sayang\n           \"SCTV\"\n\n-AzisGanzz15','cantik,sih,sayang,sctv,-azisganzz','negatif'),
(320,3,'2021-04-10 16:54:21','@pocketsizeyungi @bts_bighit SCTV gak si????','sctv,gak,si','positif'),
(321,3,'2021-04-10 16:51:21','Iiiih sereeem geliii tahu..\n????????????????????\n#TheSultanSCTV \n@Sctv \n\nSelamat berahir pekan..\nHappy Weekend..????????????????… https://t.co/XGs1VC21Va','iiiih,reeem,geliii,selamat,ahir,pekan,happy,weekend','negatif'),
(322,3,'2021-04-10 16:40:18','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(323,3,'2021-04-10 16:40:00','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(324,3,'2021-04-10 16:31:17','Jadwal Acara TV Hari Minggu 11 April 2021: Bayang Tontonan Seru di RCTI, SCTV dan GTV https://t.co/d0vDL0mspR','jadwal,acara,tv,minggu,april,bayang,tonton,seru,rcti,sctv,gtv','positif'),
(325,3,'2021-04-10 16:15:11','#KepoNotes SCTV / RCTI ?','sctv,rcti','positif'),
(326,3,'2021-04-10 16:15:00','Talk show bersama dengan Sultan Andara, Raffi Ahmad dan Sultan Bintato, Andre Taulany. Saksikan The Sultan di Visio… https://t.co/g0nsB9X4H7','talk,show,sultan,andara,raffi,ahmad,sultan,bintato,andre,taulany,saksi,the,sultan,visio','negatif'),
(327,3,'2021-04-10 16:01:34','RT @MikeAdamOnAir: .@AgnezMo’s most viewed live performances on YouTube (official account):\n\n• Diamonds (RCTI) — 6.9m\n• Sebuah Rasa (SCTV)…','s,most,viewed,live,performances,on,youtube,official,account,amonds,rcti,m,sctv','positif'),
(328,3,'2021-04-10 15:58:27','Prove me wrong: Rick Moranis did the best cover of The Police\'s \"De Do Do Do, De Da Da Da\". @Realeugenelevy #sctv','prove,me,wrong,rick,moranis,d,the,best,cover,of,the,polices,de,do,do,do,de,da,da,da','negatif'),
(329,3,'2021-04-10 15:56:40','@brocowly Lgsg nnton aja tiap hari jam 16.30 WIB, di SCTV [sbuah promo]????','lgsg,nnton,aja,jam,wib,sctv,sbuah,promo','negatif'),
(330,3,'2021-04-10 15:55:36','RT @SCTV: Apabila diriku bukanlah bagian dari semangatmu, maka setidaknya aku pernah berjuang untun mendapatkan kamu????????????\n\n#BukuHarianSeorang…','ri,mangat,juang,untun','negatif'),
(331,3,'2021-04-10 15:54:27','RT @SCTV: Pasangan #BukuHarianSeorangIstri bakal bawain lagu apa, ya? Bintang tamu &amp; host-nya pasti juga nggak kalah serrruuu!\n\nSaksikan #B…','pasang,bawain,lagu,ya,bintang,tamu,amp,host-,nggak,kalah,rrruuu,saksi','positif'),
(332,3,'2021-04-10 15:53:55','RT @SCTV: Seorang siswa SMA dan guru SD di Wonogiri  ditemukan telah terpapar covid-19. Hal ini menyebabkan pembelajaran tatap muka di kedu…','siswa,sma,guru,sd,wonogiri,temu,terpapar,covid-,menyebab,pembelajaran,tatap,muka,du','positif'),
(333,3,'2021-04-10 15:49:30','@happiywriter Sctv sj lah????','sctv,sj','negatif'),
(334,3,'2021-04-10 15:47:17','RT @sdhbucin: Igs nya sctv liat GA git? Mau bikin concert ke dua nnya dlu dia wkkwkwkw anjeng','igs,sctv,liat,ga,git,bikin,concert,n,dlu,wkkwkwkw,anjeng','positif'),
(335,3,'2021-04-10 15:44:47','@explishitconten Kepoin besokk, tiap hari jam 16.30 WIB, di SCTV [sbuah promo]????','poin,besokk,jam,wib,sctv,sbuah,promo','positif'),
(336,3,'2021-04-10 15:44:24','@januarizni Tiap hari jam 16.30 WIB, di SCTV [sbuah promo]????','jam,wib,sctv,sbuah,promo','positif'),
(337,3,'2021-04-10 15:43:29','@coolefrau Tiap hari jam 16.30 WIB, di SCTV [sbuah promo]????','jam,wib,sctv,sbuah,promo','negatif'),
(338,3,'2021-04-10 13:44:15','@SCTV awas loh gak di like admen','awas,loh,gak,like,admen','negatif'),
(339,3,'2021-04-10 13:43:41','@Syeeejin pacar sctv','pacar,sctv','positif'),
(340,3,'2021-04-10 13:42:14','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(341,3,'2021-04-10 13:39:42','Gemes sekali ortu ku bahas silsilah keluarga Maudy dan Ken di Sinetron SCTV ????','gemes,ortu,ku,bahas,silsilah,keluarga,maudy,ken,sinetron,sctv','negatif'),
(342,3,'2021-04-10 13:38:54','@SCTV KEN ????','ken','positif'),
(343,3,'2021-04-10 11:35:26','@__sssnt @ddilafnd Wkwkwkwk namanya juga sctv????','wkwkwkwk,nama,sctv','negatif'),
(344,3,'2021-04-10 11:30:34','@SCTV @UN1TY_Official Yeahhh akhirnyaaaaa UN1TY ke The Sultan lagi seneng bangett\n\nYouN1T siap siap begadang dan naikin HT nih','yeahhh,akhirnyaaaaa,unty,the,sultan,neng,bangett,yount,begadang,naikin,ht,nih','negatif'),
(345,3,'2021-04-10 11:30:22','RT @SCTV: Jangan terlalu mudah memberikan kepercayaan. Karena nggak semua orang bisa menjaga kepercayaan yang telah diberikan.\n\n#SamudraCin…','mudah,percaya,nggak,orang,menjaga,percaya','positif'),
(346,3,'2021-04-10 11:30:12','@aprlhyuckie haechan sctv','haechan,sctv','negatif'),
(347,3,'2021-04-10 11:27:27','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(348,3,'2021-04-10 11:25:19','#LEBARSimpati HADIR KEMBALI! Kali ini, hasil lelang dari para artis akan disalurkan untuk anak-anak yatim, melalui… https://t.co/Ts8aIYQhYQ','hadir,kali,hasil,lelang,artis,salur,anak-anak,yatim','positif'),
(349,3,'2021-04-10 11:21:35','@imqueenosh sctv aja gimana????','sctv,aja,gimana','positif'),
(350,3,'2021-04-10 11:19:06','Ini film apa di sctv bkin ngantuk.kaliii.','film,sctv,bkin,ngantukkaliii','negatif'),
(351,3,'2021-04-10 11:13:05','RT @SCTV: Manchester United sukses mengalahkan Granada dengan skor 2-0 pada final #UELSCTV!\n\nSetan merah berpeluang besar melaju ke semifin…','manchester,united,sukses,mengalah,granada,skor,-,final,setan,merah,peluang,melaju,mifin','negatif'),
(352,3,'2021-04-10 11:11:52','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(353,3,'2021-04-10 11:10:59','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','negatif'),
(354,3,'2021-04-10 11:07:16','@SCTV @NCTsmtown_127 NCT KONSER DI INDO??? ????','nct,konser,indo','positif'),
(355,3,'2021-04-10 11:03:51','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(356,3,'2021-04-10 10:59:19','RT @SCTV: 3 hari lagi menuju #RamadanPenuhCinta! Udah kepikiran pengin sahur pakai apa?!\n\nBerikut deretan kegiatan seru yang bisa kamu laku…','udah,pikir,pengin,sahur,pakai,deret,giat,seru,laku','positif'),
(357,3,'2021-04-10 10:57:50','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','negatif'),
(358,3,'2021-04-10 10:49:40','Cantik sih tapi sayang\n\"SCTV\"','cantik,sih,sayang,sctv','negatif'),
(359,3,'2021-04-10 10:49:08','3 hari lagi menuju #RamadanPenuhCinta! Udah kepikiran pengin sahur pakai apa?!\n\nBerikut deretan kegiatan seru yang… https://t.co/IvDSe7uV41','udah,pikir,pengin,sahur,pakai,deret,giat,seru','positif'),
(360,3,'2021-04-10 10:34:57','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','negatif'),
(361,3,'2021-04-10 10:34:55','tokped gk tayang di sctv yah??? channel tv gue yg lain burem:(','tokped,gk,tayang,sctv,yah,channel,tv,gue,yg,burem','positif'),
(362,3,'2021-04-10 10:33:37','@UN1TY_Official @SCTV Malam banget ya hyung????????','malam,banget,ya,hyung','negatif'),
(363,3,'2021-04-10 10:33:36','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(364,3,'2021-04-10 10:33:20','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(365,3,'2021-04-10 10:33:13','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(366,3,'2021-04-10 10:32:21','@SCTV @Zweitson_UN1TY @UN1TY_Official debakk, jam 00 :\')','debakk,jam','negatif'),
(367,3,'2021-04-10 10:28:32','@v0uzmevoyez AJG SCTV\nSATU UNTUK SEMUA????????????','ajg,sctv','positif'),
(368,3,'2021-04-10 10:27:11','@byunaliciaaa btw ini gue baca dn lu sctv masa????????????','btw,gue,baca,dn,lu,sctv','positif'),
(369,3,'2021-04-10 10:25:23','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(370,3,'2021-04-10 10:24:07','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','negatif'),
(371,3,'2021-04-10 10:23:51','@SCTV @UN1TY_Official 00:15 WITA :\')','wita','negatif'),
(372,3,'2021-04-10 10:23:32','@Humanxxyz1 @UN1TY_Official @SCTV Hihi oke oke','hihi,oke,oke','positif'),
(373,3,'2021-04-10 10:16:57','Aku nya HONDA\ntapi kamu nya SCTV','honda,sctv','negatif'),
(374,3,'2021-04-10 10:10:15','RT @SCTV: Terus semangat dan bangkit dari kesedihan, karena kesedihan adalah proses yang harus dilalui untuk menuju kebahagiaan???\n\n#LoveSt…','semangat,bangkit,sedih,sedih,proses,bahagia','negatif'),
(375,3,'2021-04-10 10:06:36','@snoopychies sctv????','sctv','negatif'),
(376,3,'2021-04-10 10:02:14','@BTSVotingIndo @BTS_twt Gang sctv\n\nI Vote #BTSARMY for #BestFanArmy at the 2021 #iHeartAwards (@BTS_twt)','gang,sctv,i,vote,for,at,the','negatif'),
(377,3,'2021-04-10 09:58:14','@Alredoaldrian @julystars7 @wahyoearifianto @tvindonesiawkwk Sorry ikut jb2. Ku pernah onsite di sinetron sctv gini… https://t.co/HeFIZUw7SW','sorry,jb,ku,onsite,sinetron,sctv,gin','negatif'),
(378,3,'2021-04-10 09:56:01','@snoopychies ya btul kan sctv','ya,btul,sctv','positif'),
(379,3,'2021-04-10 09:54:21','kek you think you part time di sctv ??!','kek,you,think,you,part,time,sctv','positif'),
(380,3,'2021-04-10 09:52:14','RT @SCTV: Jangan karena merasa jadi Mr.Steril kamu tak ingin mengenal seseorang, bisa jadi seseorang tersebut terkena virus cintamu~\n\n #FTV…','mrsteril,mengenal,terkena,virus,cinta','negatif'),
(381,3,'2021-04-10 09:51:49','RT @SCTV: Happy Birthday Mami Meriam Belina????????\n\nSemoga panjang umur, sehat selalu, awet mudanya, awet cantiknya, bugar, dan selalu semangat…','happy,birthday,mami,meriam,belina,moga,umur,sehat,awet,muda,awet,cantik,bugar,semangat','positif'),
(382,3,'2021-04-10 09:51:42','RT @SCTV: Jangan terlalu cepat mempercayai apa yang kamu dengar pada saat itu, karena kebohongan selalu menyebar lebih cepat dari kebenaran…','cepat,mempercayai,dengar,bohong,menyebar,cepat,benar','negatif'),
(383,3,'2021-04-10 09:51:25','RT @SCTV: LDR memang sungguh berat, namun hal itu harus dilakukan karena jarak.\n\nBiasanya hal apa yang kamu lakukan untuk mengobati rindu?…','ldr,sungguh,berat,jarak,laku,mengobati,rindu','positif'),
(384,3,'2021-04-10 09:51:19','RT @SCTV: Terus semangat dan bangkit dari kesedihan, karena kesedihan adalah proses yang harus dilalui untuk menuju kebahagiaan???\n\n#LoveSt…','semangat,bangkit,sedih,sedih,proses,bahagia','negatif'),
(385,3,'2021-04-10 09:48:02','@okkotsunarin Mikey memang sctv','mikey,sctv','negatif'),
(386,3,'2021-04-10 09:46:29','RT @UmarChelseaHsb: PPT 14 coming soon di SCTV. Keren bang @Deddy_Mizwar_ jgn lupa ges tonton PPT 14 ya ???? https://t.co/ObzRXhdLzQ','ppt,coming,soon,sctv,keren,bang,jgn,lupa,ges,tonton,ppt,ya','positif'),
(387,3,'2021-04-10 09:44:38','Jadwal 8 Besar Liga Europa Leg 1 Malam Ini Live SCTV ~ GRANADA VS MANCHESTER UNITED UEL 2021: ... Final Liga Europa… https://t.co/uTHU5vVoCV','jadwal,liga,europa,leg,malam,live,sctv,granada,vs,manchester,united,uel,final,liga,europa','negatif'),
(388,3,'2021-04-10 09:44:25','RT @SCTV: BREAKING NEWS! Gempa berkekuatan 6,7 M terjadi di Malang hingga merobohkan atap rumah sakit di Blitar. Menurut BMKG gempa tidak…','breaking,news,gempa,kekuatan,m,malang,meroboh,atap,rumah,sakit,blitar,bmkg,gempa','positif'),
(389,3,'2021-04-10 09:35:01','RT @SCTV: Terus semangat dan bangkit dari kesedihan, karena kesedihan adalah proses yang harus dilalui untuk menuju kebahagiaan???\n\n#LoveSt…','semangat,bangkit,sedih,sedih,proses,bahagia','positif'),
(390,3,'2021-04-10 09:34:56','RT @SCTV: BREAKING NEWS! Gempa berkekuatan 6,7 M terjadi di Malang hingga merobohkan atap rumah sakit di Blitar. Menurut BMKG gempa tidak…','breaking,news,gempa,kekuatan,m,malang,meroboh,atap,rumah,sakit,blitar,bmkg,gempa','negatif'),
(391,3,'2021-04-10 09:34:38','RT @AGN3ZONE: Qasim Kiani Reacted to Shake it off by @agnezmo at Harmoni My AGNEZMO SCTV\nLink video reaction: https://t.co/M8pXbLEvaa\n.\nRT…','qasim,kiani,reacted,to,shake,it,off,by,at,harmoni,my,agnezmo,sctv,link,video,reaction,rt','negatif'),
(392,3,'2021-04-10 09:30:00','Jangan terlalu mudah memberikan kepercayaan. Karena nggak semua orang bisa menjaga kepercayaan yang telah diberikan… https://t.co/qDkHGhngSO','mudah,percaya,nggak,orang,menjaga,percaya','negatif'),
(413,3,'2021-04-10 04:25:57','@UN1TY_Official @SCTV ga janji min karena ada kelas pagi????????','ga,janji,min,kelas,pagi','positif'),
(414,3,'2021-04-10 04:25:46','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(415,3,'2021-04-10 04:25:45','@UN1TY_Official @SCTV Min kenapa malam bngt? Trus nama HT nya apaan min?','min,malam,bngt,trus,nama,ht,min','negatif'),
(416,3,'2021-04-10 04:25:42','@UN1TY_Official @SCTV gas dong min','gas,min','positif'),
(417,3,'2021-04-10 04:25:42','@UN1TY_Official @SCTV ahhh kemaleman mimin ????????besok nya senin,sekolah????????????????','ahhh,maleman,mimin,besok,ninseko','positif'),
(418,3,'2021-04-10 04:25:41','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(419,3,'2021-04-10 04:25:35','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(420,3,'2021-04-10 04:25:32','@UN1TY_Official @SCTV Malem bngttt minn:\")','malem,bngttt,minn','positif'),
(421,3,'2021-04-10 04:25:31','@UN1TY_Official @SCTV min bisa liat selain dr tipi ga si?????','min,liat,dr,tipi,ga,si','positif'),
(422,3,'2021-04-10 04:25:29','@UN1TY_Official @SCTV Ada sesi ngobrol nya gaa min','sesi,ngobrol,gaa,min','positif'),
(423,3,'2021-04-10 04:25:27','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(424,3,'2021-04-10 04:25:27','@UN1TY_Official @SCTV OMAIGATTT','omaigattt','positif'),
(425,3,'2021-04-10 04:25:27','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(426,3,'2021-04-10 04:25:25','@UN1TY_Official @SCTV Insyaallah min???? tp hayuk','insyaal,min,tp,hayuk','positif'),
(427,3,'2021-04-10 04:25:23','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(428,3,'2021-04-10 04:25:19','@UN1TY_Official @SCTV Siap siap ngalong ini mah','ngalong,mah','positif'),
(429,3,'2021-04-10 04:25:18','@SCTV @UN1TY_Update @UN1TY_Official lgu restu waktuu','lgu,restu,waktuu','positif'),
(430,3,'2021-04-10 04:25:16','RT @SCTV: YOUN1T kita bakal nyanyi bareng @UN1TY_Official dan bincang-bincang seru juga bersana Dede Sunandar dan Asri Welas! Kira-kira lag…','yount,nyanyi,bareng,bincang-bincang,seru,sana,dede,sunandar,asri,welas,lag','positif'),
(431,3,'2021-04-10 04:25:15','RT @UN1TY_Official: Uwi uwiwi uwi uwiwi ???? Kembali hadir di @sctv ????? Ngalong sambil naikin HT ga nih? ????','uwi,uwiwi,uwi,uwiwi,hadir,ngalong,naikin,ht,ga,nih','negatif'),
(436,3,'2021-04-10 01:29:20','Jadi pengen nonton ftv sctv jaman dulu. Yg soundtrack nya\\n\\\"Masih kuingat selalu..\\\"\\nAku memang manusia biasaa','pengen,nonton,ftv,sctv,jam,yg,soundtrack,nyanmasih,kuingat,laluna,manusia,biasaa','negatif'),
(437,3,'2021-04-10 00:29:22','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','negatif'),
(440,3,'2021-04-10 01:20:56','RT @SCTV: Viral! Buaya besar di Bontang, bernama Riska yang dikenal akrab dan ramah seakan jadi sahabat manusia. Seperti apa penampakannya?…','viral,buaya,bontang,nama,riska,kenal,akrab,ramah,a,sahabat,manusia,penampakan','negatif'),
(441,3,'2021-04-10 01:17:17','@SCTV Dalam cerita katanya Samudra sukses,kaya tp rmhnya ga mewah, apalg dibilang mendpt penghargaan htl bintang 5… https://t.co/tIm43n8EWi','cerita,samudra,sukseskaya,tp,rmh,ga,mewah,apalg,bilang,mendpt,penghargaan,htl,bintang','positif'),
(442,3,'2021-04-10 01:13:10','RT @SCTV: Usai direnovasi, Masjid Istiqlal Jakarta siap dibuka selama Ramadan. Semua aktivitas salat sudah bisa dilakukan, namun untuk tahu…','renovasi,masjid,istiqlal,jakarta,buka,ramadan,aktivitas,salat','positif'),
(443,3,'2021-04-10 01:09:49','Jangan karena merasa jadi Mr.Steril kamu tak ingin mengenal seseorang, bisa jadi seseorang tersebut terkena virus c… https://t.co/O886z0ygF4','mrsteril,mengenal,terkena,virus,c','negatif'),
(444,3,'2021-04-10 01:07:40','RT @SCTV: Viral! Buaya besar di Bontang, bernama Riska yang dikenal akrab dan ramah seakan jadi sahabat manusia. Seperti apa penampakannya?…','viral,buaya,bontang,nama,riska,kenal,akrab,ramah,a,sahabat,manusia,penampakan','positif'),
(445,3,'2021-04-10 01:05:56','jangan lewatkan setiap hari sabtu jam 5 sore di SCTV acara Top Chef Indonesia','lewat,sabtu,jam,sore,sctv,acara,top,chef,indonesia','positif'),
(446,3,'2021-04-10 01:02:46','RT @SCTV: Viral! Buaya besar di Bontang, bernama Riska yang dikenal akrab dan ramah seakan jadi sahabat manusia. Seperti apa penampakannya?…','viral,buaya,bontang,nama,riska,kenal,akrab,ramah,a,sahabat,manusia,penampakan','positif'),
(447,3,'2021-04-10 01:00:48','RT @SCTV: Viral! Buaya besar di Bontang, bernama Riska yang dikenal akrab dan ramah seakan jadi sahabat manusia. Seperti apa penampakannya?…','viral,buaya,bontang,nama,riska,kenal,akrab,ramah,a,sahabat,manusia,penampakan','positif'),
(448,3,'2021-04-10 01:00:38','Nemu video ini jadi inget jaman masih awal-awal jadi smashblast, Ya Allah ini hari ini anniv yang ke 11 semoga seha… https://t.co/zVUsYKjG5P','ne,video,inget,jam,awal-awal,smashblast,ya,al,anniv,moga,ha','negatif'),
(449,3,'2021-04-10 00:59:54','Usai direnovasi, Masjid Istiqlal Jakarta siap dibuka selama Ramadan. Semua aktivitas salat sudah bisa dilakukan, na… https://t.co/JbfQFsBonC','renovasi,masjid,istiqlal,jakarta,buka,ramadan,aktivitas,salat,na','negatif'),
(450,3,'2021-04-10 00:57:38','Viral! Buaya besar di Bontang, bernama Riska yang dikenal akrab dan ramah seakan jadi sahabat manusia. Seperti apa… https://t.co/RrrkbAz0OA','viral,buaya,bontang,nama,riska,kenal,akrab,ramah,a,sahabat,manusia','negatif'),
(451,3,'2021-04-10 00:55:40','Pastikan kebutuhan terpenuhi, Presiden Jokowi sambangi para korban bencana di NTT. Pada kesempatan itu, Jokowi juga… https://t.co/gfBP5VrhBA','pasti,butuh,terpenuhi,presiden,jokowi,sambangi,korban,bencana,ntt,sempat,jokowi','negatif'),
(452,3,'2021-04-10 00:52:25','RT @SCTV: Yah elah, kirain udah hari Sabtu.\nKerja lagi, gaes. Mangat! ?? \n\n#SamudraCintaSCTV https://t.co/YMwJN1af6r','yah,e,kirain,udah,sabtu,kerja,gaes,mangat','negatif'),
(453,3,'2021-04-10 00:51:34','@FantomasCinema @faceyouhate I loved SCTV’s take on this in the great Network Wars episode, where Don Caballero say… https://t.co/AgNLi5mmGu','i,loved,sctvs,take,on,this,in,the,great,network,wars,episode,where,don,caballero,say','negatif'),
(454,3,'2021-04-10 00:50:12','@jaehyunkingdom @SCTV @NCTsmtown @NCTsmtown_127 Follback ya','follback,ya','positif'),
(455,3,'2021-04-10 00:35:51','@Indo_Gunner Emang bening banget min kalo yg digital, di sumatera belum digital, masih Indosiar, SCTV TVRI trans corp','emang,bening,banget,min,kalo,yg,digital,sumatera,digital,indosiar,sctv,tvri,trans,corp','positif'),
(456,3,'2021-04-10 00:34:31','RT @S_GraciaJKT48: @SCTV @N_ShaniJKT48 Miminnya GreShan-GreShan an juga ya...','mimin,greshan-greshan,an,ya','positif'),
(457,3,'2021-04-10 00:29:22','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','negatif'),
(458,3,'2021-04-10 00:28:46','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','negatif'),
(459,3,'2021-04-10 00:23:35','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','positif'),
(460,3,'2021-04-10 00:13:40','RT @CenayangFilm: Jarot dkk yang sudah 986745926191 kali muncul di SCTV akhirnya ke Netflix https://t.co/OHWa4RCsZd','jarot,dkk,kali,muncul,sctv,netflix','positif'),
(531,1,'2021-04-09 02:23:19','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','negatif'),
(532,1,'2021-04-09 02:22:36','RT @netmediatama: Close the door mang Ded... close the door...???? https://t.co/JKWRwOCniA','close,the,door,mang,ded,close,the,door','positif'),
(533,1,'2021-04-09 02:17:43','@netmediatama Sisa musim gasss lah tayangin smua laganya.','sisa,musim,gasss,tayangin,smua,laga','positif'),
(534,1,'2021-04-09 02:16:43','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','positif'),
(535,1,'2021-04-09 02:05:08','@netmediatama Akhirnya min, thanks a lot ????, calon juara UCL','min,thanks,a,lot,calon,juara,ucl','negatif'),
(536,1,'2021-04-09 02:04:07','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','negatif'),
(537,1,'2021-04-09 02:02:56','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','negatif'),
(538,1,'2021-04-09 02:02:54','RT @netmediatama: Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','positif'),
(539,1,'2021-04-09 02:01:26','I love you too sunshine, cant wait to see #EbruSahin #Reyyan #Hercai tonight #Indonesia time @netmediatama and the… https://t.co/V23oebMz9s','i,love,you,too,sunshine,cant,wait,to,e,tonight,time,and,the','negatif'),
(540,1,'2021-04-09 02:00:47','RT @netmediatama: Close the door mang Ded... close the door...???? https://t.co/JKWRwOCniA','close,the,door,mang,ded,close,the,door','positif'),
(541,1,'2021-04-09 02:00:00','Crystal Palace VS Chelsea, Sabtu 10 April 2021 Jam 23.00 WIB #NontonBolaAsiknyadiNET https://t.co/FYbfxctJkF','crystal,palace,vs,chelsea,sabtu,april,jam,wib','positif'),
(542,1,'2021-04-09 01:53:45','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #27','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(543,1,'2021-04-09 01:42:01','Jadwal Siaran Live #Bundesliga &amp; #PL Premier League Pekan Ini di NET. &amp; Mola TV #PremierLeague - Prediksi: ????… https://t.co/Bbpai5ab3E','jadwal,siar,live,amp,premier,league,pekan,net,amp,mola,tv,-,prediksi','positif'),
(544,1,'2021-04-09 01:29:35','RT @netmediatama: Close the door mang Ded... close the door...???? https://t.co/JKWRwOCniA','close,the,door,mang,ded,close,the,door','negatif'),
(545,1,'2021-04-09 01:25:14','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #26','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(546,1,'2021-04-09 01:13:59','RT @netmediatama: Arah bercandanya mau kemana sih iniii? ???????? https://t.co/ju6yPi1H8Y','arah,canda,mana,sih,iniii','negatif'),
(547,1,'2021-04-09 01:00:00','Frankfurt VS Wolfsburg, Sabtu 10 April 2021 Jam 20.00 WIB #NontonBolaAsiknyadiNET https://t.co/pjoTsdUnC8','frankfurt,vs,wolfsburg,sabtu,april,jam,wib','positif'),
(548,1,'2021-04-09 00:52:56','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #25','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','negatif'),
(549,1,'2021-04-09 00:23:04','Dukung \"Tenggelamnya Kapal Van Der Wijck sebagai Movie Of The Year\" caranya klik link terus tweet aja langsung https://t.co/Bg9wpcNhmy #24','dukung,tenggelam,kapal,van,der,wijck,movie,of,the,year,klik,link,tweet,aja,langsung','positif'),
(550,1,'2021-04-09 00:10:47','netmediatama Lost without you - Robin Thicke #TwinsNET4 #HUTNET4_21MEI','netmediatama,lost,without,you,-,robin,thicke','positif');

/*Table structure for table `objek` */

DROP TABLE IF EXISTS `objek`;

CREATE TABLE `objek` (
  `id_objek` int(11) NOT NULL AUTO_INCREMENT,
  `nama_objek` varchar(50) DEFAULT NULL,
  `id_twitter` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_objek`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `objek` */

insert  into `objek`(`id_objek`,`nama_objek`,`id_twitter`) values 
(1,'NETMEDIATAMA','@netmediatama'),
(2,'RCTI','@OfficialRCTI'),
(3,'SCTV','@SCTV');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
